import json
import datetime
from elasticsearch import Elasticsearch

es = Elasticsearch("http://localhost:9200")

def add_years_experience(document: dict) -> dict:
    """Calculates years of experience from past job durations"""
    
    # Iterate through job entries
    job_list = document.get("experience", [])
    total_years = 0
    current_year = datetime.datetime.now().year
    for job in job_list:
        
        # Get start/end dates
        start_date_str = job.get("start_date", "")
        end_date_str = job.get("end_date", "")

        # Extract start year
        try:
            start_year = int(start_date_str[-4:]) if start_date_str else 0

        except Exception:
            continue

        # Extract end year
        try:
            end_year = int(end_date_str[-4:]) if end_date_str else current_year
        except Exception:
            # Default to now for current jobs
            end_year = current_year

        # Get years per job and add to total
        years = end_year - start_year
        if years > 0:
            total_years += years

    # Append field and return the document
    document["years_experience"] = total_years
    return document

def date_fixer(date: str) -> str:
    """Fix dates using names to use set format - MM/YYYY"""

    # Make mapping of month names to numerical values
    month_map = {"jan":"01", "feb":"02", "mar":"03", "apr":"04", "may":"05", "jun":"06", "jul":"07", "aug":"08", "sep":"09", "oct":"10", "nov":"11", "dec":"12"}
    
    # Check if it needs fixing and fix it if so
    needs_fixing = False
    for key in month_map:
        if date.lower().startswith(key):
            needs_fixing = True
            break

    if needs_fixing:
        month, year = date.split(" ")[:2]
        month = month_map[month[:3].lower()] or "01"
        date = f"{month}/{year}"
    
    return date

def jsonl_to_es(jsonl_path: str = "parser_output.jsonl", index_name: str = "resume_index") -> None:
    """Reads the JSONL file generated by resume_parser.py and inserts documents into ES index"""

    # Open file and read by line
    with open(jsonl_path, "r", encoding="utf-8") as f:
        print(f"Indexing documents from {jsonl_path} into '{index_name}'")
        document_count = 0
        failure_count = 0
        for line in f:
            valid = True
            document = json.loads(line)
            
            # Flag as invalid if missing required fields
            for field in ["id", "education", "experience", "skills"]:
                if field not in document:
                    print(f"document ID {document.get('id', 'unknown')} is missing field: {field}")
                    valid = False
        
            # Remove extra fields generated by the parser
            for key in list(document.keys()):
                
                # Remove extra top-level fields
                if key not in ["id", "education", "experience", "skills", "years_experience"]:
                    print(f"document ID {document.get('id', 'unknown')} has extra field: {key}, removing it.")
                    del document[key]
                
                # Remove extra nested fields
                if key == "education":
                    for edu in document["education"]:
                        if type(edu) != dict:
                            valid = False
                        else:
                            for edu_key in list(edu.keys()):
                                if edu_key not in ["degree", "institution", "graduation_year"]:
                                    print(f"document ID {document.get('id', 'unknown')} has extra education field: {edu_key}, removing it.")
                                    del edu[edu_key]
                
                if key == "experience":
                    for exp in document["experience"]:
                        if type(exp) != dict:
                            valid = False
                        else:
                            for exp_key in list(exp.keys()):
                                if exp_key not in ["title", "start_date", "end_date"]:
                                    print(f"document ID {document.get('id', 'unknown')} has extra experience field: {exp_key}, removing it.")
                                    del exp[exp_key]
            
            # If valid, finalize and send to ES index
            if valid:

                # Fix dates in experience to be compliant with ES mapping
                for experience in document.get("experience", []):
                    
                    # Set end date to now if empty or "current"
                    if not experience.get("end_date", "") or "current" in experience.get("end_date", "").lower():
                        experience["end_date"] = datetime.datetime.now().strftime("%m/%Y")
                    
                    # Attempt to fix date formats
                    if experience.get("start_date", ""):
                        try:
                            experience["start_date"] = date_fixer(experience["start_date"])
                        except Exception:
                            pass
                    if experience.get("end_date", ""):
                        try:
                            experience["end_date"] = date_fixer(experience["end_date"])
                        except Exception:
                            pass

                document = add_years_experience(document)
                try:
                    response = es.index(index=index_name, id=document["id"], body=document)
                    document_count += 1
                except Exception as e:
                    print(f"Failed to insert document ID {document['id']}\n{e}")
                    failure_count += 1
                    continue
                print(f"Document ID {document['id']}: {response['result']}")
        print(f"Indexing complete: {document_count} / {document_count + failure_count} documents indexed.")

if __name__ == "__main__":
    jsonl_to_es()
